services:
  vue_app:
    container_name: vue_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run serve"
